# Generated by Django 6.0.3 on 2026-03-11 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=180)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('whatsapp_default_message', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color, for example #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color, for example #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('button_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color, for example #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('navbar_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color, for example #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('footer_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color, for example #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('show_prices', models.BooleanField(default=True)),
                ('show_stock', models.BooleanField(default=True)),
                ('show_brands', models.BooleanField(default=True)),
                ('show_featured_products', models.BooleanField(default=True)),
                ('show_whatsapp_button', models.BooleanField(default=True)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('show_about_section', models.BooleanField(default=True)),
                ('show_banner', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
