# Generated by Django 6.0.3 on 2026-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'name'], name='catalog_bra_is_acti_5c9548_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='catalog_bra_slug_65677f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='catalog_cat_is_acti_100145_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['is_active', 'name'], name='catalog_pro_is_acti_78b039_idx'),
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_d77ca8_idx'),
        ),
    ]
